/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface LinkItem
 */
export interface LinkItem {
    /**
     * URI of target, this will be to the next link.
     * @type {string}
     * @memberof LinkItem
     */
    href: string;
    /**
     * The relationship between source and target. The value will be `next`.
     * @type {string}
     * @memberof LinkItem
     */
    rel: string;
    /**
     * The HTTP method, the value will be `GET`.
     * @type {string}
     * @memberof LinkItem
     */
    method: string;
}

/**
 * Check if a given object implements the LinkItem interface.
 */
export function instanceOfLinkItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "href" in value;
    isInstance = isInstance && "rel" in value;
    isInstance = isInstance && "method" in value;

    return isInstance;
}

export function LinkItemFromJSON(json: any): LinkItem {
    return LinkItemFromJSONTyped(json, false);
}

export function LinkItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'href': json['href'],
        'rel': json['rel'],
        'method': json['method'],
    };
}

export function LinkItemToJSON(value?: LinkItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'href': value.href,
        'rel': value.rel,
        'method': value.method,
    };
}

