/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * 
 * @export
 */
export const TransactionTypes = {
    BatchDisbursement: 'BATCH_DISBURSEMENT',
    Disbursement: 'DISBURSEMENT',
    Payment: 'PAYMENT',
    Remittance: 'REMITTANCE',
    RemittancePayout: 'REMITTANCE_PAYOUT',
    RemittanceCollection: 'REMITTANCE_COLLECTION',
    Transfer: 'TRANSFER',
    PlatformFee: 'PLATFORM_FEE',
    Refund: 'REFUND',
    Cashback: 'CASHBACK',
    Topup: 'TOPUP',
    Withdrawal: 'WITHDRAWAL',
    Other: 'OTHER',
    XenditEnumDefaultFallback: "UNKNOWN_ENUM_VALUE"
} as const;
export type TransactionTypes = typeof TransactionTypes[keyof typeof TransactionTypes];


export function TransactionTypesFromJSON(json: any): TransactionTypes {
    return TransactionTypesFromJSONTyped(json, false);
}

export function TransactionTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionTypes {
    if (json !== "" || json !== null) {
        const key = Object.keys(TransactionTypes)[Object.values(TransactionTypes).indexOf(json)]
        return TransactionTypes[key] === undefined ?
            TransactionTypes['XenditEnumDefaultFallback'] : TransactionTypes[key]
    }
    return json as TransactionTypes;
}

export function TransactionTypesToJSON(value?: TransactionTypes | null): any {
    return value as any;
}

