/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * 
 * @export
 */
export const TransactionStatuses = {
    Success: 'SUCCESS',
    Pending: 'PENDING',
    Failed: 'FAILED',
    Reversed: 'REVERSED',
    Voided: 'VOIDED'
} as const;
export type TransactionStatuses = typeof TransactionStatuses[keyof typeof TransactionStatuses];


export function TransactionStatusesFromJSON(json: any): TransactionStatuses {
    return TransactionStatusesFromJSONTyped(json, false);
}

export function TransactionStatusesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionStatuses {
    return json as TransactionStatuses;
}

export function TransactionStatusesToJSON(value?: TransactionStatuses | null): any {
    return value as any;
}

