/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * Representing the available bank channels used for invoice-related transactions.
 * @export
 */
export const BankCode = {
    Bca: 'BCA',
    Bni: 'BNI',
    Bri: 'BRI',
    Mandiri: 'MANDIRI',
    Permata: 'PERMATA',
    Bsi: 'BSI',
    Bjb: 'BJB',
    SahabatSampoerna: 'SAHABAT_SAMPOERNA',
    Cimb: 'CIMB',
    Bnc: 'BNC',
    Hana: 'HANA',
    Muamalat: 'MUAMALAT',
    XenditEnumDefaultFallback: "UNKNOWN_ENUM_VALUE"
} as const;
export type BankCode = typeof BankCode[keyof typeof BankCode];


export function BankCodeFromJSON(json: any): BankCode {
    return BankCodeFromJSONTyped(json, false);
}

export function BankCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankCode {
    if (json !== "" || json !== null) {
        const key = Object.keys(BankCode)[Object.values(BankCode).indexOf(json)]
        return BankCode[key] === undefined ?
            BankCode['XenditEnumDefaultFallback'] : BankCode[key]
    }
    return json as BankCode;
}

export function BankCodeToJSON(value?: BankCode | null): any {
    return value as any;
}

