/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * Representing the available Direct Debit channels used for invoice-related transactions.
 * @export
 */
export const DirectDebitType = {
    BaBri: 'BA_BRI',
    DcBri: 'DC_BRI',
    DdBri: 'DD_BRI',
    DdMandiri: 'DD_MANDIRI',
    BaBpi: 'BA_BPI',
    DcBpi: 'DC_BPI',
    DdBpi: 'DD_BPI',
    BaUbp: 'BA_UBP',
    DcUbp: 'DC_UBP',
    DdUbp: 'DD_UBP',
    BcaKlikpay: 'BCA_KLIKPAY',
    BaBcaKlikpay: 'BA_BCA_KLIKPAY',
    DcBcaKlikpay: 'DC_BCA_KLIKPAY',
    DdBcaKlikpay: 'DD_BCA_KLIKPAY'
} as const;
export type DirectDebitType = typeof DirectDebitType[keyof typeof DirectDebitType];


export function DirectDebitTypeFromJSON(json: any): DirectDebitType {
    return DirectDebitTypeFromJSONTyped(json, false);
}

export function DirectDebitTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectDebitType {
    return json as DirectDebitType;
}

export function DirectDebitTypeToJSON(value?: DirectDebitType | null): any {
    return value as any;
}

