/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * Representing the available eWallet channels used for invoice-related transactions.
 * @export
 */
export const EwalletType = {
    Ovo: 'OVO',
    Dana: 'DANA',
    Linkaja: 'LINKAJA',
    Paymaya: 'PAYMAYA',
    Shopeepay: 'SHOPEEPAY',
    Gcash: 'GCASH',
    Grabpay: 'GRABPAY',
    Astrapay: 'ASTRAPAY',
    Nexcash: 'NEXCASH',
    Jeniuspay: 'JENIUSPAY',
    Momo: 'MOMO',
    Zalopay: 'ZALOPAY',
    Viettelpay: 'VIETTELPAY',
    Vnptwallet: 'VNPTWALLET',
    Appota: 'APPOTA',
    Linepay: 'LINEPAY',
    Truemoney: 'TRUEMONEY',
    Wechatpay: 'WECHATPAY',
    Touchngo: 'TOUCHNGO',
    XenditEnumDefaultFallback: "UNKNOWN_ENUM_VALUE"
} as const;
export type EwalletType = typeof EwalletType[keyof typeof EwalletType];


export function EwalletTypeFromJSON(json: any): EwalletType {
    return EwalletTypeFromJSONTyped(json, false);
}

export function EwalletTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EwalletType {
    if (json !== "" || json !== null) {
        const key = Object.keys(EwalletType)[Object.values(EwalletType).indexOf(json)]
        return EwalletType[key] === undefined ?
            EwalletType['XenditEnumDefaultFallback'] : EwalletType[key]
    }
    return json as EwalletType;
}

export function EwalletTypeToJSON(value?: EwalletType | null): any {
    return value as any;
}

