/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { EwalletType } from './EwalletType';
import {
    EwalletTypeFromJSON,
    EwalletTypeFromJSONTyped,
    EwalletTypeToJSON,
} from './EwalletType';

/**
 * An object representing e-wallet details for invoices.
 * @export
 * @interface Ewallet
 */
export interface Ewallet {
    /**
     * 
     * @type {EwalletType}
     * @memberof Ewallet
     */
    ewalletType: EwalletType;
}

/**
 * Check if a given object implements the Ewallet interface.
 */
export function instanceOfEwallet(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ewalletType" in value;

    return isInstance;
}

export function EwalletFromJSON(json: any): Ewallet {
    return EwalletFromJSONTyped(json, false);
}

export function EwalletFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ewallet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ewalletType': EwalletTypeFromJSON(json['ewallet_type']),
    };
}

export function EwalletToJSON(value?: Ewallet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ewallet_type': EwalletTypeToJSON(value.ewalletType),
    };
}

