/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * An object representing an item within an invoice.
 * @export
 * @interface InvoiceCallbackItem
 */
export interface InvoiceCallbackItem {
    /**
     * The name of the item.
     * @type {string}
     * @memberof InvoiceCallbackItem
     */
    name: string;
    /**
     * The price of the item.
     * @type {number}
     * @memberof InvoiceCallbackItem
     */
    price: number;
    /**
     * The quantity of the item. Must be greater than or equal to 0.
     * @type {number}
     * @memberof InvoiceCallbackItem
     */
    quantity: number;
    /**
     * The URL associated with the item.
     * @type {string}
     * @memberof InvoiceCallbackItem
     */
    url?: string;
    /**
     * The category of the item.
     * @type {string}
     * @memberof InvoiceCallbackItem
     */
    category?: string;
}

/**
 * Check if a given object implements the InvoiceCallbackItem interface.
 */
export function instanceOfInvoiceCallbackItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "price" in value;
    isInstance = isInstance && "quantity" in value;

    return isInstance;
}

export function InvoiceCallbackItemFromJSON(json: any): InvoiceCallbackItem {
    return InvoiceCallbackItemFromJSONTyped(json, false);
}

export function InvoiceCallbackItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceCallbackItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'price': json['price'],
        'quantity': json['quantity'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'category': !exists(json, 'category') ? undefined : json['category'],
    };
}

export function InvoiceCallbackItemToJSON(value?: InvoiceCallbackItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'price': value.price,
        'quantity': value.quantity,
        'url': value.url,
        'category': value.category,
    };
}

