/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * Representing the payment method used for an invoice.
 * @export
 */
export const InvoicePaymentMethod = {
    Pool: 'POOL',
    CallbackVirtualAccount: 'CALLBACK_VIRTUAL_ACCOUNT',
    CreditCard: 'CREDIT_CARD',
    RetailOutlet: 'RETAIL_OUTLET',
    QrCode: 'QR_CODE',
    Qris: 'QRIS',
    Ewallet: 'EWALLET',
    DirectDebit: 'DIRECT_DEBIT',
    BankTransfer: 'BANK_TRANSFER',
    Paylater: 'PAYLATER'
} as const;
export type InvoicePaymentMethod = typeof InvoicePaymentMethod[keyof typeof InvoicePaymentMethod];


export function InvoicePaymentMethodFromJSON(json: any): InvoicePaymentMethod {
    return InvoicePaymentMethodFromJSONTyped(json, false);
}

export function InvoicePaymentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoicePaymentMethod {
    return json as InvoicePaymentMethod;
}

export function InvoicePaymentMethodToJSON(value?: InvoicePaymentMethod | null): any {
    return value as any;
}

