/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * Representing a notification channel for sending messages.
 * @export
 */
export const NotificationChannel = {
    Email: 'email',
    Sms: 'sms',
    Whatsapp: 'whatsapp',
    Viber: 'viber'
} as const;
export type NotificationChannel = typeof NotificationChannel[keyof typeof NotificationChannel];


export function NotificationChannelFromJSON(json: any): NotificationChannel {
    return NotificationChannelFromJSONTyped(json, false);
}

export function NotificationChannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationChannel {
    return json as NotificationChannel;
}

export function NotificationChannelToJSON(value?: NotificationChannel | null): any {
    return value as any;
}

