/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * Representing the available QR Code channels used for invoice-related transactions.
 * @export
 */
export const QrCodeType = {
    Qris: 'QRIS',
    Promptpay: 'PROMPTPAY'
} as const;
export type QrCodeType = typeof QrCodeType[keyof typeof QrCodeType];


export function QrCodeTypeFromJSON(json: any): QrCodeType {
    return QrCodeTypeFromJSONTyped(json, false);
}

export function QrCodeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): QrCodeType {
    return json as QrCodeType;
}

export function QrCodeTypeToJSON(value?: QrCodeType | null): any {
    return value as any;
}

