/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * Representing the available QR Code channels used for invoice-related transactions.
 * @export
 */
export const QrCodeType = {
    Qris: 'QRIS',
    Promptpay: 'PROMPTPAY',
    Qrph: 'QRPH',
    XenditEnumDefaultFallback: "UNKNOWN_ENUM_VALUE"
} as const;
export type QrCodeType = typeof QrCodeType[keyof typeof QrCodeType];


export function QrCodeTypeFromJSON(json: any): QrCodeType {
    return QrCodeTypeFromJSONTyped(json, false);
}

export function QrCodeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): QrCodeType {
    if (json !== "" || json !== null) {
        const key = Object.keys(QrCodeType)[Object.values(QrCodeType).indexOf(json)]
        return QrCodeType[key] === undefined ?
            QrCodeType['XenditEnumDefaultFallback'] : QrCodeType[key]
    }
    return json as QrCodeType;
}

export function QrCodeTypeToJSON(value?: QrCodeType | null): any {
    return value as any;
}

