/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * Representing the available retail outlet channels used for invoice-related transactions.
 * @export
 */
export const RetailOutletName = {
    Alfamart: 'ALFAMART',
    Indomaret: 'INDOMARET',
    _7Eleven: '7ELEVEN',
    Cebuana: 'CEBUANA',
    DpEcpayLoan: 'DP_ECPAY_LOAN',
    DpMlhuillier: 'DP_MLHUILLIER',
    DpPalawan: 'DP_PALAWAN',
    DpEcpaySchool: 'DP_ECPAY_SCHOOL',
    Lbc: 'LBC'
} as const;
export type RetailOutletName = typeof RetailOutletName[keyof typeof RetailOutletName];


export function RetailOutletNameFromJSON(json: any): RetailOutletName {
    return RetailOutletNameFromJSONTyped(json, false);
}

export function RetailOutletNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetailOutletName {
    return json as RetailOutletName;
}

export function RetailOutletNameToJSON(value?: RetailOutletName | null): any {
    return value as any;
}

