/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface ServerError
 */
export interface ServerError {
    /**
     * 
     * @type {string}
     * @memberof ServerError
     */
    errorCode: ServerErrorErrorCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof ServerError
     */
    message: string;
}


/**
 * @export
 */
export const ServerErrorErrorCodeEnum = {
    ServerError: 'SERVER_ERROR'
} as const;
export type ServerErrorErrorCodeEnum = typeof ServerErrorErrorCodeEnum[keyof typeof ServerErrorErrorCodeEnum];


/**
 * Check if a given object implements the ServerError interface.
 */
export function instanceOfServerError(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "errorCode" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ServerErrorFromJSON(json: any): ServerError {
    return ServerErrorFromJSONTyped(json, false);
}

export function ServerErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': json['error_code'],
        'message': json['message'],
    };
}

export function ServerErrorToJSON(value?: ServerError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error_code': value.errorCode,
        'message': value.message,
    };
}

