/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { DigitalPayoutChannelProperties } from './DigitalPayoutChannelProperties';
import {
    DigitalPayoutChannelPropertiesFromJSON,
    DigitalPayoutChannelPropertiesFromJSONTyped,
    DigitalPayoutChannelPropertiesToJSON,
} from './DigitalPayoutChannelProperties';
import type { ReceiptNotification } from './ReceiptNotification';
import {
    ReceiptNotificationFromJSON,
    ReceiptNotificationFromJSONTyped,
    ReceiptNotificationToJSON,
} from './ReceiptNotification';

/**
 * Information needed by Xendit to send money to the destination channel provided
 * @export
 * @interface CreatePayoutRequest
 */
export interface CreatePayoutRequest {
    /**
     * A client defined payout identifier
     * @type {string}
     * @memberof CreatePayoutRequest
     */
    referenceId: string;
    /**
     * Channel code of selected destination bank or e-wallet
     * @type {string}
     * @memberof CreatePayoutRequest
     */
    channelCode: string;
    /**
     * 
     * @type {DigitalPayoutChannelProperties}
     * @memberof CreatePayoutRequest
     */
    channelProperties: DigitalPayoutChannelProperties;
    /**
     * Amount to be sent to the destination account and should be a multiple of the minimum increment for the selected channel
     * @type {number}
     * @memberof CreatePayoutRequest
     */
    amount: number;
    /**
     * Description to send with the payout, the recipient may see this e.g., in their bank statement (if supported) or in email receipts we send on your behalf
     * @type {string}
     * @memberof CreatePayoutRequest
     */
    description?: string;
    /**
     * Currency of the destination channel using ISO-4217 currency code
     * @type {string}
     * @memberof CreatePayoutRequest
     */
    currency: string;
    /**
     * 
     * @type {ReceiptNotification}
     * @memberof CreatePayoutRequest
     */
    receiptNotification?: ReceiptNotification;
    /**
     * Object of additional information you may use
     * @type {object}
     * @memberof CreatePayoutRequest
     */
    metadata?: object;
}

/**
 * Check if a given object implements the CreatePayoutRequest interface.
 */
export function instanceOfCreatePayoutRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "referenceId" in value;
    isInstance = isInstance && "channelCode" in value;
    isInstance = isInstance && "channelProperties" in value;
    isInstance = isInstance && "amount" in value;
    isInstance = isInstance && "currency" in value;

    return isInstance;
}

export function CreatePayoutRequestFromJSON(json: any): CreatePayoutRequest {
    return CreatePayoutRequestFromJSONTyped(json, false);
}

export function CreatePayoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePayoutRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'referenceId': json['reference_id'],
        'channelCode': json['channel_code'],
        'channelProperties': DigitalPayoutChannelPropertiesFromJSON(json['channel_properties']),
        'amount': json['amount'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'currency': json['currency'],
        'receiptNotification': !exists(json, 'receipt_notification') ? undefined : ReceiptNotificationFromJSON(json['receipt_notification']),
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function CreatePayoutRequestToJSON(value?: CreatePayoutRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reference_id': value.referenceId,
        'channel_code': value.channelCode,
        'channel_properties': DigitalPayoutChannelPropertiesToJSON(value.channelProperties),
        'amount': value.amount,
        'description': value.description,
        'currency': value.currency,
        'receipt_notification': ReceiptNotificationToJSON(value.receiptNotification),
        'metadata': value.metadata,
    };
}

