/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { CardChannelProperties } from './CardChannelProperties';
import {
    CardChannelPropertiesFromJSON,
    CardChannelPropertiesFromJSONTyped,
    CardChannelPropertiesToJSON,
} from './CardChannelProperties';
import type { CardParametersCardInformation } from './CardParametersCardInformation';
import {
    CardParametersCardInformationFromJSON,
    CardParametersCardInformationFromJSONTyped,
    CardParametersCardInformationToJSON,
} from './CardParametersCardInformation';

/**
 * 
 * @export
 * @interface CardParameters
 */
export interface CardParameters {
    /**
     * 
     * @type {string}
     * @memberof CardParameters
     */
    currency: string;
    /**
     * 
     * @type {CardChannelProperties}
     * @memberof CardParameters
     */
    channelProperties?: CardChannelProperties | null;
    /**
     * 
     * @type {CardParametersCardInformation}
     * @memberof CardParameters
     */
    cardInformation?: CardParametersCardInformation;
}

/**
 * Check if a given object implements the CardParameters interface.
 */
export function instanceOfCardParameters(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "currency" in value;

    return isInstance;
}

export function CardParametersFromJSON(json: any): CardParameters {
    return CardParametersFromJSONTyped(json, false);
}

export function CardParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'channelProperties': !exists(json, 'channel_properties') ? undefined : CardChannelPropertiesFromJSON(json['channel_properties']),
        'cardInformation': !exists(json, 'card_information') ? undefined : CardParametersCardInformationFromJSON(json['card_information']),
    };
}

export function CardParametersToJSON(value?: CardParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currency': value.currency,
        'channel_properties': CardChannelPropertiesToJSON(value.channelProperties),
        'card_information': CardParametersCardInformationToJSON(value.cardInformation),
    };
}

