/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface CardVerificationResultsThreeDSecure
 */
export interface CardVerificationResultsThreeDSecure {
    /**
     * 
     * @type {string}
     * @memberof CardVerificationResultsThreeDSecure
     */
    threeDSecureFlow?: CardVerificationResultsThreeDSecureThreeDSecureFlowEnum;
    /**
     * 
     * @type {string}
     * @memberof CardVerificationResultsThreeDSecure
     */
    eciCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardVerificationResultsThreeDSecure
     */
    threeDSecureResult?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardVerificationResultsThreeDSecure
     */
    threeDSecureResultReason?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardVerificationResultsThreeDSecure
     */
    threeDSecureVersion?: string | null;
}


/**
 * @export
 */
export const CardVerificationResultsThreeDSecureThreeDSecureFlowEnum = {
    Challenge: 'CHALLENGE',
    Frictionless: 'FRICTIONLESS'
} as const;
export type CardVerificationResultsThreeDSecureThreeDSecureFlowEnum = typeof CardVerificationResultsThreeDSecureThreeDSecureFlowEnum[keyof typeof CardVerificationResultsThreeDSecureThreeDSecureFlowEnum];


/**
 * Check if a given object implements the CardVerificationResultsThreeDSecure interface.
 */
export function instanceOfCardVerificationResultsThreeDSecure(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CardVerificationResultsThreeDSecureFromJSON(json: any): CardVerificationResultsThreeDSecure {
    return CardVerificationResultsThreeDSecureFromJSONTyped(json, false);
}

export function CardVerificationResultsThreeDSecureFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardVerificationResultsThreeDSecure {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'threeDSecureFlow': !exists(json, 'three_d_secure_flow') ? undefined : json['three_d_secure_flow'],
        'eciCode': !exists(json, 'eci_code') ? undefined : json['eci_code'],
        'threeDSecureResult': !exists(json, 'three_d_secure_result') ? undefined : json['three_d_secure_result'],
        'threeDSecureResultReason': !exists(json, 'three_d_secure_result_reason') ? undefined : json['three_d_secure_result_reason'],
        'threeDSecureVersion': !exists(json, 'three_d_secure_version') ? undefined : json['three_d_secure_version'],
    };
}

export function CardVerificationResultsThreeDSecureToJSON(value?: CardVerificationResultsThreeDSecure | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'three_d_secure_flow': value.threeDSecureFlow,
        'eci_code': value.eciCode,
        'three_d_secure_result': value.threeDSecureResult,
        'three_d_secure_result_reason': value.threeDSecureResultReason,
        'three_d_secure_version': value.threeDSecureVersion,
    };
}

