/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * Card Information
 * @export
 * @interface CardParametersCardInformation
 */
export interface CardParametersCardInformation {
    /**
     * 
     * @type {string}
     * @memberof CardParametersCardInformation
     */
    cardNumber: string;
    /**
     * Card expiry month in MM format
     * @type {string}
     * @memberof CardParametersCardInformation
     */
    expiryMonth: string;
    /**
     * Card expiry month in YY format
     * @type {string}
     * @memberof CardParametersCardInformation
     */
    expiryYear: string;
    /**
     * Cardholder name
     * @type {string}
     * @memberof CardParametersCardInformation
     */
    cardholderName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CardParametersCardInformation
     */
    cvv?: string | null;
}

/**
 * Check if a given object implements the CardParametersCardInformation interface.
 */
export function instanceOfCardParametersCardInformation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "cardNumber" in value;
    isInstance = isInstance && "expiryMonth" in value;
    isInstance = isInstance && "expiryYear" in value;

    return isInstance;
}

export function CardParametersCardInformationFromJSON(json: any): CardParametersCardInformation {
    return CardParametersCardInformationFromJSONTyped(json, false);
}

export function CardParametersCardInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardParametersCardInformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cardNumber': json['card_number'],
        'expiryMonth': json['expiry_month'],
        'expiryYear': json['expiry_year'],
        'cardholderName': !exists(json, 'cardholder_name') ? undefined : json['cardholder_name'],
        'cvv': !exists(json, 'cvv') ? undefined : json['cvv'],
    };
}

export function CardParametersCardInformationToJSON(value?: CardParametersCardInformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'card_number': value.cardNumber,
        'expiry_month': value.expiryMonth,
        'expiry_year': value.expiryYear,
        'cardholder_name': value.cardholderName,
        'cvv': value.cvv,
    };
}

