/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * Contains objects of the support currencies and its respective limits per transaction
 * @export
 * @interface ChannelAmountLimitsAllOf
 */
export interface ChannelAmountLimitsAllOf {
    /**
     * Currency supported by the payment channel
     * @type {string}
     * @memberof ChannelAmountLimitsAllOf
     */
    currency?: string;
    /**
     * The minimum allowed transaction amount for the payment channel
     * @type {number}
     * @memberof ChannelAmountLimitsAllOf
     */
    minLimit?: number;
    /**
     * The minimum allowed transaction amount for the payment channel
     * @type {number}
     * @memberof ChannelAmountLimitsAllOf
     */
    maxLimit?: number;
}

/**
 * Check if a given object implements the ChannelAmountLimitsAllOf interface.
 */
export function instanceOfChannelAmountLimitsAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChannelAmountLimitsAllOfFromJSON(json: any): ChannelAmountLimitsAllOf {
    return ChannelAmountLimitsAllOfFromJSONTyped(json, false);
}

export function ChannelAmountLimitsAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChannelAmountLimitsAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'minLimit': !exists(json, 'min_limit') ? undefined : json['min_limit'],
        'maxLimit': !exists(json, 'max_limit') ? undefined : json['max_limit'],
    };
}

export function ChannelAmountLimitsAllOfToJSON(value?: ChannelAmountLimitsAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'currency': value.currency,
        'min_limit': value.minLimit,
        'max_limit': value.maxLimit,
    };
}

