/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface CreatePaymentMethod503Response
 */
export interface CreatePaymentMethod503Response {
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentMethod503Response
     */
    errorCode?: CreatePaymentMethod503ResponseErrorCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreatePaymentMethod503Response
     */
    message?: string;
}


/**
 * @export
 */
export const CreatePaymentMethod503ResponseErrorCodeEnum = {
    ChannelUnavailable: 'CHANNEL_UNAVAILABLE',
    OtpDeliveryError: 'OTP_DELIVERY_ERROR'
} as const;
export type CreatePaymentMethod503ResponseErrorCodeEnum = typeof CreatePaymentMethod503ResponseErrorCodeEnum[keyof typeof CreatePaymentMethod503ResponseErrorCodeEnum];


/**
 * Check if a given object implements the CreatePaymentMethod503Response interface.
 */
export function instanceOfCreatePaymentMethod503Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreatePaymentMethod503ResponseFromJSON(json: any): CreatePaymentMethod503Response {
    return CreatePaymentMethod503ResponseFromJSONTyped(json, false);
}

export function CreatePaymentMethod503ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePaymentMethod503Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': !exists(json, 'error_code') ? undefined : json['error_code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function CreatePaymentMethod503ResponseToJSON(value?: CreatePaymentMethod503Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error_code': value.errorCode,
        'message': value.message,
    };
}

