/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { DirectDebitChannelCode } from './DirectDebitChannelCode';
import {
    DirectDebitChannelCodeFromJSON,
    DirectDebitChannelCodeFromJSONTyped,
    DirectDebitChannelCodeToJSON,
} from './DirectDebitChannelCode';
import type { DirectDebitChannelProperties } from './DirectDebitChannelProperties';
import {
    DirectDebitChannelPropertiesFromJSON,
    DirectDebitChannelPropertiesFromJSONTyped,
    DirectDebitChannelPropertiesToJSON,
} from './DirectDebitChannelProperties';

/**
 * 
 * @export
 * @interface DirectDebitParameters
 */
export interface DirectDebitParameters {
    /**
     * 
     * @type {DirectDebitChannelCode}
     * @memberof DirectDebitParameters
     */
    channelCode: DirectDebitChannelCode;
    /**
     * 
     * @type {DirectDebitChannelProperties}
     * @memberof DirectDebitParameters
     */
    channelProperties: DirectDebitChannelProperties | null;
}

/**
 * Check if a given object implements the DirectDebitParameters interface.
 */
export function instanceOfDirectDebitParameters(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "channelCode" in value;
    isInstance = isInstance && "channelProperties" in value;

    return isInstance;
}

export function DirectDebitParametersFromJSON(json: any): DirectDebitParameters {
    return DirectDebitParametersFromJSONTyped(json, false);
}

export function DirectDebitParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectDebitParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'channelCode': DirectDebitChannelCodeFromJSON(json['channel_code']),
        'channelProperties': DirectDebitChannelPropertiesFromJSON(json['channel_properties']),
    };
}

export function DirectDebitParametersToJSON(value?: DirectDebitParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'channel_code': DirectDebitChannelCodeToJSON(value.channelCode),
        'channel_properties': DirectDebitChannelPropertiesToJSON(value.channelProperties),
    };
}

