/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface DirectDebitDebitCard
 */
export interface DirectDebitDebitCard {
    /**
     * Mobile number of the customer registered to the partner channel
     * @type {string}
     * @memberof DirectDebitDebitCard
     */
    mobileNumber?: string | null;
    /**
     * Last four digits of the debit card
     * @type {string}
     * @memberof DirectDebitDebitCard
     */
    cardLastFour?: string | null;
    /**
     * Expiry month and year of the debit card (in MM/YY format)
     * @type {string}
     * @memberof DirectDebitDebitCard
     */
    cardExpiry?: string | null;
    /**
     * Email address of the customer that is registered to the partner channel
     * @type {string}
     * @memberof DirectDebitDebitCard
     */
    email?: string | null;
}

/**
 * Check if a given object implements the DirectDebitDebitCard interface.
 */
export function instanceOfDirectDebitDebitCard(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DirectDebitDebitCardFromJSON(json: any): DirectDebitDebitCard {
    return DirectDebitDebitCardFromJSONTyped(json, false);
}

export function DirectDebitDebitCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectDebitDebitCard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mobileNumber': !exists(json, 'mobile_number') ? undefined : json['mobile_number'],
        'cardLastFour': !exists(json, 'card_last_four') ? undefined : json['card_last_four'],
        'cardExpiry': !exists(json, 'card_expiry') ? undefined : json['card_expiry'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function DirectDebitDebitCardToJSON(value?: DirectDebitDebitCard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mobile_number': value.mobileNumber,
        'card_last_four': value.cardLastFour,
        'card_expiry': value.cardExpiry,
        'email': value.email,
    };
}

