/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface GetAllPaymentMethods400Response
 */
export interface GetAllPaymentMethods400Response {
    /**
     * 
     * @type {string}
     * @memberof GetAllPaymentMethods400Response
     */
    errorCode?: GetAllPaymentMethods400ResponseErrorCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof GetAllPaymentMethods400Response
     */
    message?: string;
}


/**
 * @export
 */
export const GetAllPaymentMethods400ResponseErrorCodeEnum = {
    AccountAccessBlocked: 'ACCOUNT_ACCESS_BLOCKED',
    AddressValidationFailed: 'ADDRESS_VALIDATION_FAILED',
    AmountMismatched: 'AMOUNT_MISMATCHED',
    ApiValidationError: 'API_VALIDATION_ERROR',
    AuthenticationFailed: 'AUTHENTICATION_FAILED',
    AuthenticationRequired: 'AUTHENTICATION_REQUIRED',
    BrandNotSupported: 'BRAND_NOT_SUPPORTED',
    CardDeclined: 'CARD_DECLINED',
    ChannelCodeNotSupportedError: 'CHANNEL_CODE_NOT_SUPPORTED_ERROR',
    CofCombinationNotAllowedError: 'COF_COMBINATION_NOT_ALLOWED_ERROR',
    CurrencyMismatched: 'CURRENCY_MISMATCHED',
    CustomerNotFoundError: 'CUSTOMER_NOT_FOUND_ERROR',
    CustomerPaymentMethodMismatched: 'CUSTOMER_PAYMENT_METHOD_MISMATCHED',
    DeclinedByIssuer: 'DECLINED_BY_ISSUER',
    DeclinedByProcessor: 'DECLINED_BY_PROCESSOR',
    DuplicatedFixedPaymentInstrument: 'DUPLICATED_FIXED_PAYMENT_INSTRUMENT',
    DuplicateReference: 'DUPLICATE_REFERENCE',
    ExpiredCard: 'EXPIRED_CARD',
    ExpiredOtpError: 'EXPIRED_OTP_ERROR',
    FeatureNotActivated: 'FEATURE_NOT_ACTIVATED',
    InactiveOrUnauthorizedCard: 'INACTIVE_OR_UNAUTHORIZED_CARD',
    InactivePaymentMethod: 'INACTIVE_PAYMENT_METHOD',
    IncorrectAmount: 'INCORRECT_AMOUNT',
    InsufficientBalance: 'INSUFFICIENT_BALANCE',
    InvalidAccountDetails: 'INVALID_ACCOUNT_DETAILS',
    InvalidCvv: 'INVALID_CVV',
    InvalidLinkedAccount: 'INVALID_LINKED_ACCOUNT',
    InvalidOtpError: 'INVALID_OTP_ERROR',
    InvalidPaymentMethod: 'INVALID_PAYMENT_METHOD',
    InvalidToken: 'INVALID_TOKEN',
    LinkedAccountNotFoundError: 'LINKED_ACCOUNT_NOT_FOUND_ERROR',
    MaxAccountLinking: 'MAX_ACCOUNT_LINKING',
    MaxAmountLimitError: 'MAX_AMOUNT_LIMIT_ERROR',
    MaxOtpAttemptsError: 'MAX_OTP_ATTEMPTS_ERROR',
    NotSupportedByChannel: 'NOT_SUPPORTED_BY_CHANNEL',
    OperationNotAllowed: 'OPERATION_NOT_ALLOWED',
    OtpDeliveryError: 'OTP_DELIVERY_ERROR',
    PartnerChannelError: 'PARTNER_CHANNEL_ERROR',
    PaymentMethodNotFoundError: 'PAYMENT_METHOD_NOT_FOUND_ERROR',
    PaymentMethodNotSupported: 'PAYMENT_METHOD_NOT_SUPPORTED',
    PaymentMethodReusabilityInvalid: 'PAYMENT_METHOD_REUSABILITY_INVALID',
    PaymentMethodStatusInvalid: 'PAYMENT_METHOD_STATUS_INVALID',
    PaymentMethodTypeInvalid: 'PAYMENT_METHOD_TYPE_INVALID'
} as const;
export type GetAllPaymentMethods400ResponseErrorCodeEnum = typeof GetAllPaymentMethods400ResponseErrorCodeEnum[keyof typeof GetAllPaymentMethods400ResponseErrorCodeEnum];


/**
 * Check if a given object implements the GetAllPaymentMethods400Response interface.
 */
export function instanceOfGetAllPaymentMethods400Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetAllPaymentMethods400ResponseFromJSON(json: any): GetAllPaymentMethods400Response {
    return GetAllPaymentMethods400ResponseFromJSONTyped(json, false);
}

export function GetAllPaymentMethods400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllPaymentMethods400Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': !exists(json, 'error_code') ? undefined : json['error_code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function GetAllPaymentMethods400ResponseToJSON(value?: GetAllPaymentMethods400Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error_code': value.errorCode,
        'message': value.message,
    };
}

