/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { OverTheCounterChannelCode } from './OverTheCounterChannelCode';
import {
    OverTheCounterChannelCodeFromJSON,
    OverTheCounterChannelCodeFromJSONTyped,
    OverTheCounterChannelCodeToJSON,
} from './OverTheCounterChannelCode';
import type { OverTheCounterChannelProperties } from './OverTheCounterChannelProperties';
import {
    OverTheCounterChannelPropertiesFromJSON,
    OverTheCounterChannelPropertiesFromJSONTyped,
    OverTheCounterChannelPropertiesToJSON,
} from './OverTheCounterChannelProperties';

/**
 * 
 * @export
 * @interface OverTheCounterParameters
 */
export interface OverTheCounterParameters {
    /**
     * 
     * @type {number}
     * @memberof OverTheCounterParameters
     */
    amount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof OverTheCounterParameters
     */
    currency?: string;
    /**
     * 
     * @type {OverTheCounterChannelCode}
     * @memberof OverTheCounterParameters
     */
    channelCode: OverTheCounterChannelCode;
    /**
     * 
     * @type {OverTheCounterChannelProperties}
     * @memberof OverTheCounterParameters
     */
    channelProperties: OverTheCounterChannelProperties;
}

/**
 * Check if a given object implements the OverTheCounterParameters interface.
 */
export function instanceOfOverTheCounterParameters(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "channelCode" in value;
    isInstance = isInstance && "channelProperties" in value;

    return isInstance;
}

export function OverTheCounterParametersFromJSON(json: any): OverTheCounterParameters {
    return OverTheCounterParametersFromJSONTyped(json, false);
}

export function OverTheCounterParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): OverTheCounterParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'channelCode': OverTheCounterChannelCodeFromJSON(json['channel_code']),
        'channelProperties': OverTheCounterChannelPropertiesFromJSON(json['channel_properties']),
    };
}

export function OverTheCounterParametersToJSON(value?: OverTheCounterParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'currency': value.currency,
        'channel_code': OverTheCounterChannelCodeToJSON(value.channelCode),
        'channel_properties': OverTheCounterChannelPropertiesToJSON(value.channelProperties),
    };
}

