/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { OverTheCounterChannelPropertiesUpdate } from './OverTheCounterChannelPropertiesUpdate';
import {
    OverTheCounterChannelPropertiesUpdateFromJSON,
    OverTheCounterChannelPropertiesUpdateFromJSONTyped,
    OverTheCounterChannelPropertiesUpdateToJSON,
} from './OverTheCounterChannelPropertiesUpdate';

/**
 * 
 * @export
 * @interface OverTheCounterUpdateParameters
 */
export interface OverTheCounterUpdateParameters {
    /**
     * 
     * @type {number}
     * @memberof OverTheCounterUpdateParameters
     */
    amount?: number | null;
    /**
     * 
     * @type {OverTheCounterChannelPropertiesUpdate}
     * @memberof OverTheCounterUpdateParameters
     */
    channelProperties?: OverTheCounterChannelPropertiesUpdate;
}

/**
 * Check if a given object implements the OverTheCounterUpdateParameters interface.
 */
export function instanceOfOverTheCounterUpdateParameters(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OverTheCounterUpdateParametersFromJSON(json: any): OverTheCounterUpdateParameters {
    return OverTheCounterUpdateParametersFromJSONTyped(json, false);
}

export function OverTheCounterUpdateParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): OverTheCounterUpdateParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'channelProperties': !exists(json, 'channel_properties') ? undefined : OverTheCounterChannelPropertiesUpdateFromJSON(json['channel_properties']),
    };
}

export function OverTheCounterUpdateParametersToJSON(value?: OverTheCounterUpdateParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'channel_properties': OverTheCounterChannelPropertiesUpdateToJSON(value.channelProperties),
    };
}

