/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * 
 * @export
 */
export const PaymentMethodStatus = {
    Active: 'ACTIVE',
    Expired: 'EXPIRED',
    Inactive: 'INACTIVE',
    Pending: 'PENDING',
    RequiresAction: 'REQUIRES_ACTION',
    Failed: 'FAILED'
} as const;
export type PaymentMethodStatus = typeof PaymentMethodStatus[keyof typeof PaymentMethodStatus];


export function PaymentMethodStatusFromJSON(json: any): PaymentMethodStatus {
    return PaymentMethodStatusFromJSONTyped(json, false);
}

export function PaymentMethodStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethodStatus {
    return json as PaymentMethodStatus;
}

export function PaymentMethodStatusToJSON(value?: PaymentMethodStatus | null): any {
    return value as any;
}

