/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface PaymentMethodAuthParameters
 */
export interface PaymentMethodAuthParameters {
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodAuthParameters
     */
    authCode: string;
}

/**
 * Check if a given object implements the PaymentMethodAuthParameters interface.
 */
export function instanceOfPaymentMethodAuthParameters(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "authCode" in value;

    return isInstance;
}

export function PaymentMethodAuthParametersFromJSON(json: any): PaymentMethodAuthParameters {
    return PaymentMethodAuthParametersFromJSONTyped(json, false);
}

export function PaymentMethodAuthParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethodAuthParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authCode': json['auth_code'],
    };
}

export function PaymentMethodAuthParametersToJSON(value?: PaymentMethodAuthParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'auth_code': value.authCode,
    };
}

