const CardStatus = require('../../src/card/card_status');

const VALID_CARD_NUM = '4000000000000002';
const VALID_EXP_MNTH = '12';
const VALID_EXP_YR = '2020';
const VALID_CVN = '123';
const VALID_TOKEN_ID = '5d8c611f6f86303720b1f16f';
const VALID_TOKEN_RESPONSE = {
  id: VALID_TOKEN_ID,
  masked_card_number: '400000XXXXXX0002',
  status: CardStatus.VERIFIED,
};
const VALID_CHARGE_ID = '5d8d7fc86f86303720b1f30b';
const AMOUNT = 10000;
const EXT_ID = '123';
const VALID_CRE_CHARGE_RESPONSE = {
  id: VALID_CHARGE_ID,
  authorized_amount: AMOUNT,
  capture_amount: AMOUNT,
  external_id: EXT_ID,
};
const VALID_CAP_CHARGE_RESPONSE = {
  id: VALID_CHARGE_ID,
  capture_amount: AMOUNT,
};
const VALID_AUTH_ID = '5d8d7fa86f86303720b1f309';
const VALID_CRE_AUTH_RESPONSE = {
  id: VALID_CHARGE_ID,
  authorized_amount: AMOUNT,
  external_id: EXT_ID,
};
const VALID_REFUND_ID = '5d8d9479a4271a6c9bc5b2ec';
const VALID_REFUND_RESPONSE = {
  id: VALID_REFUND_ID,
  external_id: EXT_ID,
  credit_card_charge_id: VALID_CHARGE_ID,
  amount: AMOUNT,
};

const VALID_PROMOTION_ID = '36ab1517-208a-4f22-b155-96fb101cb378';
const VALID_PROMOTION_REF_ID = 'BRI_20_JAN';
const VALID_PROMOTION_PROMO_CODE = 'TEST';
const VALID_PROMOTION_BUSINESS_ID = '5e61664b3dba955c203d232e';
const VALID_PROMOTION_DESCRIPTION = '20% discount applied for all BRI cards';
const VALID_PROMOTION_START_TIME = '2022-01-01 00:00:00.000Z';
const VALID_PROMOTION_END_TIME = '2022-02-01 00:00:00.000Z';
const VALID_PROMOTION_STATUS = 'ACTIVE';
const VALID_PROMOTION_BIN_LIST = ['400000', '460000'];
const VALID_PROMOTION_DISCOUNT_PERCENTAGE = 20;
const VALID_PROMOTION_DISCOUNT_AMOUNT = 200;
const VALID_PROMOTION_CHANNEL_CODE = 'BRI';
const VALID_PROMOTION_CURRENCY = 'IDR';
const VALID_PROMOTION_MIN_AMOUNT = 1200;
const VALID_PROMOTION_MAX_AMOUNT = 5000;
const VALID_PROMOTION_RESPONSE = {
  id: VALID_PROMOTION_ID,
  business_id: VALID_PROMOTION_BUSINESS_ID,
  reference_id: VALID_PROMOTION_REF_ID,
  description: VALID_PROMOTION_DESCRIPTION,
  start_time: VALID_PROMOTION_START_TIME,
  end_time: VALID_PROMOTION_END_TIME,
  status: VALID_PROMOTION_STATUS,
  bin_list: VALID_PROMOTION_BIN_LIST,
  discount_percent: VALID_PROMOTION_DISCOUNT_PERCENTAGE,
  channel_code: VALID_PROMOTION_CHANNEL_CODE,
  currency: VALID_PROMOTION_CURRENCY,
  min_original_amount: VALID_PROMOTION_MIN_AMOUNT,
  max_discount_amount: VALID_PROMOTION_MAX_AMOUNT,
};

module.exports = {
  VALID_CARD_NUM,
  VALID_EXP_MNTH,
  VALID_EXP_YR,
  VALID_CVN,
  VALID_TOKEN_ID,
  VALID_TOKEN_RESPONSE,
  VALID_CHARGE_ID,
  AMOUNT,
  EXT_ID,
  VALID_CRE_CHARGE_RESPONSE,
  VALID_CAP_CHARGE_RESPONSE,
  VALID_AUTH_ID,
  VALID_CRE_AUTH_RESPONSE,
  VALID_REFUND_RESPONSE,
  VALID_REFUND_ID,
  VALID_PROMOTION_RESPONSE,
  VALID_PROMOTION_ID,
  VALID_PROMOTION_REF_ID,
  VALID_PROMOTION_PROMO_CODE,
  VALID_PROMOTION_BUSINESS_ID,
  VALID_PROMOTION_DESCRIPTION,
  VALID_PROMOTION_START_TIME,
  VALID_PROMOTION_END_TIME,
  VALID_PROMOTION_STATUS,
  VALID_PROMOTION_BIN_LIST,
  VALID_PROMOTION_DISCOUNT_PERCENTAGE,
  VALID_PROMOTION_DISCOUNT_AMOUNT,
  VALID_PROMOTION_CHANNEL_CODE,
  VALID_PROMOTION_CURRENCY,
  VALID_PROMOTION_MIN_AMOUNT,
  VALID_PROMOTION_MAX_AMOUNT,
};
