module.exports = {
  types: 'types',
  statuses: 'statuses',
  channelCategories: 'channel_categories',
  createdDateFrom: 'created[gte]',
  createdDateTo: 'created[lte]',
  referenceId: 'reference_id',
  productId: 'product_id',
  accountIdentifier: 'account_identifier',
  currency: 'currency',
  amount: 'amount',
  updatedDateFrom: 'updated[gte]',
  updatedDateTo: 'updated[lte]',
  limit: 'limit',
  afterId: 'after_id',
  beforeId: 'before_id',
  searchType: 'search_type',
  searchValue: 'search_value',
};
