/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * 
 * @export
 */
export const AddressStatus = {
    Active: 'ACTIVE',
    Deleted: 'DELETED',
    XenditEnumDefaultFallback: "UNKNOWN_ENUM_VALUE"
} as const;
export type AddressStatus = typeof AddressStatus[keyof typeof AddressStatus];


export function AddressStatusFromJSON(json: any): AddressStatus {
    return AddressStatusFromJSONTyped(json, false);
}

export function AddressStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressStatus {
    if (json !== "" || json !== null) {
        const key = Object.keys(AddressStatus)[Object.values(AddressStatus).indexOf(json)]
        return AddressStatus[key] === undefined ?
            AddressStatus['XenditEnumDefaultFallback'] : AddressStatus[key]
    }
    return json as AddressStatus;
}

export function AddressStatusToJSON(value?: AddressStatus | null): any {
    return value as any;
}

