/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * 
 * @export
 */
export const AddressStatus = {
    Active: 'ACTIVE',
    Deleted: 'DELETED'
} as const;
export type AddressStatus = typeof AddressStatus[keyof typeof AddressStatus];


export function AddressStatusFromJSON(json: any): AddressStatus {
    return AddressStatusFromJSONTyped(json, false);
}

export function AddressStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressStatus {
    return json as AddressStatus;
}

export function AddressStatusToJSON(value?: AddressStatus | null): any {
    return value as any;
}

