/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * 
 * @export
 */
export const EndCustomerStatus = {
    Active: 'ACTIVE',
    Inactive: 'INACTIVE',
    Pending: 'PENDING',
    Blocked: 'BLOCKED',
    Deleted: 'DELETED',
    XenditEnumDefaultFallback: "UNKNOWN_ENUM_VALUE"
} as const;
export type EndCustomerStatus = typeof EndCustomerStatus[keyof typeof EndCustomerStatus];


export function EndCustomerStatusFromJSON(json: any): EndCustomerStatus {
    return EndCustomerStatusFromJSONTyped(json, false);
}

export function EndCustomerStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): EndCustomerStatus {
    if (json !== "" || json !== null) {
        const key = Object.keys(EndCustomerStatus)[Object.values(EndCustomerStatus).indexOf(json)]
        return EndCustomerStatus[key] === undefined ?
            EndCustomerStatus['XenditEnumDefaultFallback'] : EndCustomerStatus[key]
    }
    return json as EndCustomerStatus;
}

export function EndCustomerStatusToJSON(value?: EndCustomerStatus | null): any {
    return value as any;
}

