/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * 
 * @export
 */
export const IdentityAccountType = {
    BankAccount: 'BANK_ACCOUNT',
    Ewallet: 'EWALLET',
    CreditCard: 'CREDIT_CARD',
    PayLater: 'PAY_LATER',
    Otc: 'OTC',
    QrCode: 'QR_CODE'
} as const;
export type IdentityAccountType = typeof IdentityAccountType[keyof typeof IdentityAccountType];


export function IdentityAccountTypeFromJSON(json: any): IdentityAccountType {
    return IdentityAccountTypeFromJSONTyped(json, false);
}

export function IdentityAccountTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityAccountType {
    return json as IdentityAccountType;
}

export function IdentityAccountTypeToJSON(value?: IdentityAccountType | null): any {
    return value as any;
}

