/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { KYCDocumentSubType } from './KYCDocumentSubType';
import {
    KYCDocumentSubTypeFromJSON,
    KYCDocumentSubTypeFromJSONTyped,
    KYCDocumentSubTypeToJSON,
} from './KYCDocumentSubType';
import type { KYCDocumentType } from './KYCDocumentType';
import {
    KYCDocumentTypeFromJSON,
    KYCDocumentTypeFromJSONTyped,
    KYCDocumentTypeToJSON,
} from './KYCDocumentType';

/**
 * 
 * @export
 * @interface KYCDocumentResponse
 */
export interface KYCDocumentResponse {
    /**
     * 
     * @type {string}
     * @memberof KYCDocumentResponse
     */
    country: string;
    /**
     * 
     * @type {KYCDocumentType}
     * @memberof KYCDocumentResponse
     */
    type: KYCDocumentType;
    /**
     * 
     * @type {KYCDocumentSubType}
     * @memberof KYCDocumentResponse
     */
    subType: KYCDocumentSubType;
    /**
     * 
     * @type {string}
     * @memberof KYCDocumentResponse
     */
    documentName: string | null;
    /**
     * 
     * @type {string}
     * @memberof KYCDocumentResponse
     */
    documentNumber: string | null;
    /**
     * 
     * @type {string}
     * @memberof KYCDocumentResponse
     */
    expiresAt: string | null;
    /**
     * 
     * @type {string}
     * @memberof KYCDocumentResponse
     */
    holderName: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof KYCDocumentResponse
     */
    documentImages: Array<string> | null;
}

/**
 * Check if a given object implements the KYCDocumentResponse interface.
 */
export function instanceOfKYCDocumentResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "country" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "subType" in value;
    isInstance = isInstance && "documentName" in value;
    isInstance = isInstance && "documentNumber" in value;
    isInstance = isInstance && "expiresAt" in value;
    isInstance = isInstance && "holderName" in value;
    isInstance = isInstance && "documentImages" in value;

    return isInstance;
}

export function KYCDocumentResponseFromJSON(json: any): KYCDocumentResponse {
    return KYCDocumentResponseFromJSONTyped(json, false);
}

export function KYCDocumentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KYCDocumentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'country': json['country'],
        'type': KYCDocumentTypeFromJSON(json['type']),
        'subType': KYCDocumentSubTypeFromJSON(json['sub_type']),
        'documentName': json['document_name'],
        'documentNumber': json['document_number'],
        'expiresAt': json['expires_at'],
        'holderName': json['holder_name'],
        'documentImages': json['document_images'],
    };
}

export function KYCDocumentResponseToJSON(value?: KYCDocumentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'country': value.country,
        'type': KYCDocumentTypeToJSON(value.type),
        'sub_type': KYCDocumentSubTypeToJSON(value.subType),
        'document_name': value.documentName,
        'document_number': value.documentNumber,
        'expires_at': value.expiresAt,
        'holder_name': value.holderName,
        'document_images': value.documentImages,
    };
}

