/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface CreateRefund404Response
 */
export interface CreateRefund404Response {
    /**
     * 
     * @type {string}
     * @memberof CreateRefund404Response
     */
    errorCode?: CreateRefund404ResponseErrorCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateRefund404Response
     */
    message?: string;
}


/**
 * @export
 */
export const CreateRefund404ResponseErrorCodeEnum = {
    DataNotFound: 'DATA_NOT_FOUND'
} as const;
export type CreateRefund404ResponseErrorCodeEnum = typeof CreateRefund404ResponseErrorCodeEnum[keyof typeof CreateRefund404ResponseErrorCodeEnum];


/**
 * Check if a given object implements the CreateRefund404Response interface.
 */
export function instanceOfCreateRefund404Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateRefund404ResponseFromJSON(json: any): CreateRefund404Response {
    return CreateRefund404ResponseFromJSONTyped(json, false);
}

export function CreateRefund404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRefund404Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': !exists(json, 'error_code') ? undefined : json['error_code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function CreateRefund404ResponseToJSON(value?: CreateRefund404Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error_code': value.errorCode,
        'message': value.message,
    };
}

