/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface CreateRefund503Response
 */
export interface CreateRefund503Response {
    /**
     * 
     * @type {string}
     * @memberof CreateRefund503Response
     */
    errorCode?: CreateRefund503ResponseErrorCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateRefund503Response
     */
    message?: string;
}


/**
 * @export
 */
export const CreateRefund503ResponseErrorCodeEnum = {
    ChannelUnavailable: 'CHANNEL_UNAVAILABLE',
    OtpDeliveryError: 'OTP_DELIVERY_ERROR'
} as const;
export type CreateRefund503ResponseErrorCodeEnum = typeof CreateRefund503ResponseErrorCodeEnum[keyof typeof CreateRefund503ResponseErrorCodeEnum];


/**
 * Check if a given object implements the CreateRefund503Response interface.
 */
export function instanceOfCreateRefund503Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateRefund503ResponseFromJSON(json: any): CreateRefund503Response {
    return CreateRefund503ResponseFromJSONTyped(json, false);
}

export function CreateRefund503ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRefund503Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': !exists(json, 'error_code') ? undefined : json['error_code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function CreateRefund503ResponseToJSON(value?: CreateRefund503Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error_code': value.errorCode,
        'message': value.message,
    };
}

