/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface CreateRefund403Response
 */
export interface CreateRefund403Response {
    /**
     * 
     * @type {string}
     * @memberof CreateRefund403Response
     */
    errorCode?: CreateRefund403ResponseErrorCodeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateRefund403Response
     */
    message?: string;
}


/**
 * @export
 */
export const CreateRefund403ResponseErrorCodeEnum = {
    Unauthorized: 'UNAUTHORIZED'
} as const;
export type CreateRefund403ResponseErrorCodeEnum = typeof CreateRefund403ResponseErrorCodeEnum[keyof typeof CreateRefund403ResponseErrorCodeEnum];


/**
 * Check if a given object implements the CreateRefund403Response interface.
 */
export function instanceOfCreateRefund403Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateRefund403ResponseFromJSON(json: any): CreateRefund403Response {
    return CreateRefund403ResponseFromJSONTyped(json, false);
}

export function CreateRefund403ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRefund403Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': !exists(json, 'error_code') ? undefined : json['error_code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function CreateRefund403ResponseToJSON(value?: CreateRefund403Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error_code': value.errorCode,
        'message': value.message,
    };
}

