/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { Capture } from './Capture';
import {
    CaptureFromJSON,
    CaptureFromJSONTyped,
    CaptureToJSON,
} from './Capture';

/**
 * 
 * @export
 * @interface CaptureListResponse
 */
export interface CaptureListResponse {
    /**
     * 
     * @type {Array<Capture>}
     * @memberof CaptureListResponse
     */
    data: Array<Capture>;
    /**
     * 
     * @type {boolean}
     * @memberof CaptureListResponse
     */
    hasMore: boolean;
}

/**
 * Check if a given object implements the CaptureListResponse interface.
 */
export function instanceOfCaptureListResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "hasMore" in value;

    return isInstance;
}

export function CaptureListResponseFromJSON(json: any): CaptureListResponse {
    return CaptureListResponseFromJSONTyped(json, false);
}

export function CaptureListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CaptureListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(CaptureFromJSON)),
        'hasMore': json['has_more'],
    };
}

export function CaptureListResponseToJSON(value?: CaptureListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(CaptureToJSON)),
        'has_more': value.hasMore,
    };
}

