/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { PaymentMethod } from './PaymentMethod';
import {
    PaymentMethodFromJSON,
    PaymentMethodFromJSONTyped,
    PaymentMethodToJSON,
} from './PaymentMethod';

/**
 * 
 * @export
 * @interface Capture
 */
export interface Capture {
    /**
     * 
     * @type {string}
     * @memberof Capture
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Capture
     */
    paymentRequestId: string;
    /**
     * 
     * @type {string}
     * @memberof Capture
     */
    paymentId: string;
    /**
     * 
     * @type {string}
     * @memberof Capture
     */
    referenceId: string;
    /**
     * 
     * @type {string}
     * @memberof Capture
     */
    currency: string;
    /**
     * 
     * @type {number}
     * @memberof Capture
     */
    authorizedAmount: number;
    /**
     * 
     * @type {number}
     * @memberof Capture
     */
    capturedAmount: number;
    /**
     * 
     * @type {string}
     * @memberof Capture
     */
    status: CaptureStatusEnum;
    /**
     * 
     * @type {PaymentMethod}
     * @memberof Capture
     */
    paymentMethod: PaymentMethod;
    /**
     * 
     * @type {string}
     * @memberof Capture
     */
    failureCode: string | null;
    /**
     * 
     * @type {string}
     * @memberof Capture
     */
    customerId: string | null;
    /**
     * 
     * @type {object}
     * @memberof Capture
     */
    metadata: object | null;
    /**
     * 
     * @type {object}
     * @memberof Capture
     */
    channelProperties: object | null;
    /**
     * 
     * @type {string}
     * @memberof Capture
     */
    created: string;
    /**
     * 
     * @type {string}
     * @memberof Capture
     */
    updated: string;
}


/**
 * @export
 */
export const CaptureStatusEnum = {
    Succeeded: 'SUCCEEDED',
    Failed: 'FAILED'
} as const;
export type CaptureStatusEnum = typeof CaptureStatusEnum[keyof typeof CaptureStatusEnum];


/**
 * Check if a given object implements the Capture interface.
 */
export function instanceOfCapture(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "paymentRequestId" in value;
    isInstance = isInstance && "paymentId" in value;
    isInstance = isInstance && "referenceId" in value;
    isInstance = isInstance && "currency" in value;
    isInstance = isInstance && "authorizedAmount" in value;
    isInstance = isInstance && "capturedAmount" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "paymentMethod" in value;
    isInstance = isInstance && "failureCode" in value;
    isInstance = isInstance && "customerId" in value;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "channelProperties" in value;
    isInstance = isInstance && "created" in value;
    isInstance = isInstance && "updated" in value;

    return isInstance;
}

export function CaptureFromJSON(json: any): Capture {
    return CaptureFromJSONTyped(json, false);
}

export function CaptureFromJSONTyped(json: any, ignoreDiscriminator: boolean): Capture {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'paymentRequestId': json['payment_request_id'],
        'paymentId': json['payment_id'],
        'referenceId': json['reference_id'],
        'currency': json['currency'],
        'authorizedAmount': json['authorized_amount'],
        'capturedAmount': json['captured_amount'],
        'status': json['status'],
        'paymentMethod': PaymentMethodFromJSON(json['payment_method']),
        'failureCode': json['failure_code'],
        'customerId': json['customer_id'],
        'metadata': json['metadata'],
        'channelProperties': json['channel_properties'],
        'created': json['created'],
        'updated': json['updated'],
    };
}

export function CaptureToJSON(value?: Capture | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'payment_request_id': value.paymentRequestId,
        'payment_id': value.paymentId,
        'reference_id': value.referenceId,
        'currency': value.currency,
        'authorized_amount': value.authorizedAmount,
        'captured_amount': value.capturedAmount,
        'status': value.status,
        'payment_method': PaymentMethodToJSON(value.paymentMethod),
        'failure_code': value.failureCode,
        'customer_id': value.customerId,
        'metadata': value.metadata,
        'channel_properties': value.channelProperties,
        'created': value.created,
        'updated': value.updated,
    };
}

