/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * Card Channel Code
 * @export
 */
export const CardChannelCode = {
    Gpn: 'GPN',
    XenditEnumDefaultFallback: "UNKNOWN_ENUM_VALUE"
} as const;
export type CardChannelCode = typeof CardChannelCode[keyof typeof CardChannelCode];


export function CardChannelCodeFromJSON(json: any): CardChannelCode {
    return CardChannelCodeFromJSONTyped(json, false);
}

export function CardChannelCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardChannelCode {
    if (json !== "" || json !== null) {
        const key = Object.keys(CardChannelCode)[Object.values(CardChannelCode).indexOf(json)]
        return CardChannelCode[key] === undefined ?
            CardChannelCode['XenditEnumDefaultFallback'] : CardChannelCode[key]
    }
    return json as CardChannelCode;
}

export function CardChannelCodeToJSON(value?: CardChannelCode | null): any {
    return value as any;
}

