/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * Direct Debit Debit Card Channel Properties
 * @export
 * @interface DirectDebitChannelPropertiesDebitCard
 */
export interface DirectDebitChannelPropertiesDebitCard {
    /**
     * Mobile number of the customer registered to the partner channel
     * @type {string}
     * @memberof DirectDebitChannelPropertiesDebitCard
     */
    mobileNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof DirectDebitChannelPropertiesDebitCard
     */
    accountNumber?: string;
    /**
     * Last four digits of the debit card
     * @type {string}
     * @memberof DirectDebitChannelPropertiesDebitCard
     */
    cardLastFour?: string;
    /**
     * Expiry month and year of the debit card (in MM/YY format)
     * @type {string}
     * @memberof DirectDebitChannelPropertiesDebitCard
     */
    cardExpiry?: string;
    /**
     * Email address of the customer that is registered to the partner channel
     * @type {string}
     * @memberof DirectDebitChannelPropertiesDebitCard
     */
    email?: string;
}

/**
 * Check if a given object implements the DirectDebitChannelPropertiesDebitCard interface.
 */
export function instanceOfDirectDebitChannelPropertiesDebitCard(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DirectDebitChannelPropertiesDebitCardFromJSON(json: any): DirectDebitChannelPropertiesDebitCard {
    return DirectDebitChannelPropertiesDebitCardFromJSONTyped(json, false);
}

export function DirectDebitChannelPropertiesDebitCardFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectDebitChannelPropertiesDebitCard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mobileNumber': !exists(json, 'mobile_number') ? undefined : json['mobile_number'],
        'accountNumber': !exists(json, 'account_number') ? undefined : json['account_number'],
        'cardLastFour': !exists(json, 'card_last_four') ? undefined : json['card_last_four'],
        'cardExpiry': !exists(json, 'card_expiry') ? undefined : json['card_expiry'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function DirectDebitChannelPropertiesDebitCardToJSON(value?: DirectDebitChannelPropertiesDebitCard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mobile_number': value.mobileNumber,
        'account_number': value.accountNumber,
        'card_last_four': value.cardLastFour,
        'card_expiry': value.cardExpiry,
        'email': value.email,
    };
}

