/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface DirectDebitBankAccount
 */
export interface DirectDebitBankAccount {
    /**
     * 
     * @type {string}
     * @memberof DirectDebitBankAccount
     */
    maskedBankAccountNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DirectDebitBankAccount
     */
    bankAccountHash?: string | null;
}

/**
 * Check if a given object implements the DirectDebitBankAccount interface.
 */
export function instanceOfDirectDebitBankAccount(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DirectDebitBankAccountFromJSON(json: any): DirectDebitBankAccount {
    return DirectDebitBankAccountFromJSONTyped(json, false);
}

export function DirectDebitBankAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectDebitBankAccount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'maskedBankAccountNumber': !exists(json, 'masked_bank_account_number') ? undefined : json['masked_bank_account_number'],
        'bankAccountHash': !exists(json, 'bank_account_hash') ? undefined : json['bank_account_hash'],
    };
}

export function DirectDebitBankAccountToJSON(value?: DirectDebitBankAccount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'masked_bank_account_number': value.maskedBankAccountNumber,
        'bank_account_hash': value.bankAccountHash,
    };
}

