/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * 
 * @export
 */
export const DirectDebitType = {
    DebitCard: 'DEBIT_CARD',
    BankAccount: 'BANK_ACCOUNT',
    BankRedirect: 'BANK_REDIRECT'
} as const;
export type DirectDebitType = typeof DirectDebitType[keyof typeof DirectDebitType];


export function DirectDebitTypeFromJSON(json: any): DirectDebitType {
    return DirectDebitTypeFromJSONTyped(json, false);
}

export function DirectDebitTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DirectDebitType {
    return json as DirectDebitType;
}

export function DirectDebitTypeToJSON(value?: DirectDebitType | null): any {
    return value as any;
}

