/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * EWallet Account Properties
 * @export
 * @interface EWalletAccount
 */
export interface EWalletAccount {
    /**
     * Name of the eWallet account holder. The value is null if unavailableName of the eWallet account holder. The value is null if unavailable
     * @type {string}
     * @memberof EWalletAccount
     */
    name?: string | null;
    /**
     * Identifier from eWallet provider e.g. phone number. The value is null if unavailable
     * @type {string}
     * @memberof EWalletAccount
     */
    accountDetails?: string | null;
    /**
     * The main balance amount on eWallet account provided from eWallet provider. The value is null if unavailable
     * @type {number}
     * @memberof EWalletAccount
     */
    balance?: number | null;
    /**
     * The point balance amount on eWallet account. Applicable only on some eWallet provider that has point system. The value is null if unavailabl
     * @type {number}
     * @memberof EWalletAccount
     */
    pointBalance?: number | null;
}

/**
 * Check if a given object implements the EWalletAccount interface.
 */
export function instanceOfEWalletAccount(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EWalletAccountFromJSON(json: any): EWalletAccount {
    return EWalletAccountFromJSONTyped(json, false);
}

export function EWalletAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): EWalletAccount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'accountDetails': !exists(json, 'account_details') ? undefined : json['account_details'],
        'balance': !exists(json, 'balance') ? undefined : json['balance'],
        'pointBalance': !exists(json, 'point_balance') ? undefined : json['point_balance'],
    };
}

export function EWalletAccountToJSON(value?: EWalletAccount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'account_details': value.accountDetails,
        'balance': value.balance,
        'point_balance': value.pointBalance,
    };
}

