/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * Over The Counter Channel Code
 * @export
 */
export const OverTheCounterChannelCode = {
    _7Eleven: '7ELEVEN',
    _7ElevenCliqq: '7ELEVEN_CLIQQ',
    Cebuana: 'CEBUANA',
    Ecpay: 'ECPAY',
    Palawan: 'PALAWAN',
    Mlhuillier: 'MLHUILLIER',
    EcpayDragonloan: 'ECPAY_DRAGONLOAN',
    Lbc: 'LBC',
    EcpaySchool: 'ECPAY_SCHOOL',
    RdPawnshop: 'RD_PAWNSHOP',
    Cvm: 'CVM',
    Ussc: 'USSC',
    SmBills: 'SM_BILLS',
    RobinsonsBills: 'ROBINSONS_BILLS',
    Alfamart: 'ALFAMART',
    Indomaret: 'INDOMARET'
} as const;
export type OverTheCounterChannelCode = typeof OverTheCounterChannelCode[keyof typeof OverTheCounterChannelCode];


export function OverTheCounterChannelCodeFromJSON(json: any): OverTheCounterChannelCode {
    return OverTheCounterChannelCodeFromJSONTyped(json, false);
}

export function OverTheCounterChannelCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): OverTheCounterChannelCode {
    return json as OverTheCounterChannelCode;
}

export function OverTheCounterChannelCodeToJSON(value?: OverTheCounterChannelCode | null): any {
    return value as any;
}

