/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface PaymentRequestShippingInformation
 */
export interface PaymentRequestShippingInformation {
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestShippingInformation
     */
    country: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestShippingInformation
     */
    streetLine1?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestShippingInformation
     */
    streetLine2?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestShippingInformation
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestShippingInformation
     */
    provinceState?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestShippingInformation
     */
    postalCode?: string;
}

/**
 * Check if a given object implements the PaymentRequestShippingInformation interface.
 */
export function instanceOfPaymentRequestShippingInformation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "country" in value;

    return isInstance;
}

export function PaymentRequestShippingInformationFromJSON(json: any): PaymentRequestShippingInformation {
    return PaymentRequestShippingInformationFromJSONTyped(json, false);
}

export function PaymentRequestShippingInformationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRequestShippingInformation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'country': json['country'],
        'streetLine1': !exists(json, 'street_line1') ? undefined : json['street_line1'],
        'streetLine2': !exists(json, 'street_line2') ? undefined : json['street_line2'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'provinceState': !exists(json, 'province_state') ? undefined : json['province_state'],
        'postalCode': !exists(json, 'postal_code') ? undefined : json['postal_code'],
    };
}

export function PaymentRequestShippingInformationToJSON(value?: PaymentRequestShippingInformation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'country': value.country,
        'street_line1': value.streetLine1,
        'street_line2': value.streetLine2,
        'city': value.city,
        'province_state': value.provinceState,
        'postal_code': value.postalCode,
    };
}

