/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { Card } from './Card';
import {
    CardFromJSON,
    CardFromJSONTyped,
    CardToJSON,
} from './Card';
import type { DirectDebit } from './DirectDebit';
import {
    DirectDebitFromJSON,
    DirectDebitFromJSONTyped,
    DirectDebitToJSON,
} from './DirectDebit';
import type { EWallet } from './EWallet';
import {
    EWalletFromJSON,
    EWalletFromJSONTyped,
    EWalletToJSON,
} from './EWallet';
import type { OverTheCounter } from './OverTheCounter';
import {
    OverTheCounterFromJSON,
    OverTheCounterFromJSONTyped,
    OverTheCounterToJSON,
} from './OverTheCounter';
import type { PaymentMethodReusability } from './PaymentMethodReusability';
import {
    PaymentMethodReusabilityFromJSON,
    PaymentMethodReusabilityFromJSONTyped,
    PaymentMethodReusabilityToJSON,
} from './PaymentMethodReusability';
import type { PaymentMethodStatus } from './PaymentMethodStatus';
import {
    PaymentMethodStatusFromJSON,
    PaymentMethodStatusFromJSONTyped,
    PaymentMethodStatusToJSON,
} from './PaymentMethodStatus';
import type { PaymentMethodType } from './PaymentMethodType';
import {
    PaymentMethodTypeFromJSON,
    PaymentMethodTypeFromJSONTyped,
    PaymentMethodTypeToJSON,
} from './PaymentMethodType';
import type { QRCode } from './QRCode';
import {
    QRCodeFromJSON,
    QRCodeFromJSONTyped,
    QRCodeToJSON,
} from './QRCode';
import type { VirtualAccount } from './VirtualAccount';
import {
    VirtualAccountFromJSON,
    VirtualAccountFromJSONTyped,
    VirtualAccountToJSON,
} from './VirtualAccount';

/**
 * 
 * @export
 * @interface PaymentMethod
 */
export interface PaymentMethod {
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    id: string;
    /**
     * 
     * @type {PaymentMethodType}
     * @memberof PaymentMethod
     */
    type: PaymentMethodType;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    updated?: string;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    referenceId?: string;
    /**
     * 
     * @type {Card}
     * @memberof PaymentMethod
     */
    card?: Card | null;
    /**
     * 
     * @type {DirectDebit}
     * @memberof PaymentMethod
     */
    directDebit?: DirectDebit | null;
    /**
     * 
     * @type {EWallet}
     * @memberof PaymentMethod
     */
    ewallet?: EWallet | null;
    /**
     * 
     * @type {OverTheCounter}
     * @memberof PaymentMethod
     */
    overTheCounter?: OverTheCounter | null;
    /**
     * 
     * @type {VirtualAccount}
     * @memberof PaymentMethod
     */
    virtualAccount?: VirtualAccount | null;
    /**
     * 
     * @type {QRCode}
     * @memberof PaymentMethod
     */
    qrCode?: QRCode | null;
    /**
     * 
     * @type {PaymentMethodReusability}
     * @memberof PaymentMethod
     */
    reusability: PaymentMethodReusability;
    /**
     * 
     * @type {PaymentMethodStatus}
     * @memberof PaymentMethod
     */
    status: PaymentMethodStatus;
    /**
     * 
     * @type {object}
     * @memberof PaymentMethod
     */
    metadata?: object | null;
}

/**
 * Check if a given object implements the PaymentMethod interface.
 */
export function instanceOfPaymentMethod(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "reusability" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function PaymentMethodFromJSON(json: any): PaymentMethod {
    return PaymentMethodFromJSONTyped(json, false);
}

export function PaymentMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': PaymentMethodTypeFromJSON(json['type']),
        'created': !exists(json, 'created') ? undefined : json['created'],
        'updated': !exists(json, 'updated') ? undefined : json['updated'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'referenceId': !exists(json, 'reference_id') ? undefined : json['reference_id'],
        'card': !exists(json, 'card') ? undefined : CardFromJSON(json['card']),
        'directDebit': !exists(json, 'direct_debit') ? undefined : DirectDebitFromJSON(json['direct_debit']),
        'ewallet': !exists(json, 'ewallet') ? undefined : EWalletFromJSON(json['ewallet']),
        'overTheCounter': !exists(json, 'over_the_counter') ? undefined : OverTheCounterFromJSON(json['over_the_counter']),
        'virtualAccount': !exists(json, 'virtual_account') ? undefined : VirtualAccountFromJSON(json['virtual_account']),
        'qrCode': !exists(json, 'qr_code') ? undefined : QRCodeFromJSON(json['qr_code']),
        'reusability': PaymentMethodReusabilityFromJSON(json['reusability']),
        'status': PaymentMethodStatusFromJSON(json['status']),
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function PaymentMethodToJSON(value?: PaymentMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': PaymentMethodTypeToJSON(value.type),
        'created': value.created,
        'updated': value.updated,
        'description': value.description,
        'reference_id': value.referenceId,
        'card': CardToJSON(value.card),
        'direct_debit': DirectDebitToJSON(value.directDebit),
        'ewallet': EWalletToJSON(value.ewallet),
        'over_the_counter': OverTheCounterToJSON(value.overTheCounter),
        'virtual_account': VirtualAccountToJSON(value.virtualAccount),
        'qr_code': QRCodeToJSON(value.qrCode),
        'reusability': PaymentMethodReusabilityToJSON(value.reusability),
        'status': PaymentMethodStatusToJSON(value.status),
        'metadata': value.metadata,
    };
}

