/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
/**
 * 
 * @export
 * @interface PaymentRequestParametersChannelPropertiesAllOf
 */
export interface PaymentRequestParametersChannelPropertiesAllOf {
    /**
     * Three digit code written on the back of the card (usually called CVV/CVN).
     * @type {string}
     * @memberof PaymentRequestParametersChannelPropertiesAllOf
     */
    cvv?: string;
}

/**
 * Check if a given object implements the PaymentRequestParametersChannelPropertiesAllOf interface.
 */
export function instanceOfPaymentRequestParametersChannelPropertiesAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaymentRequestParametersChannelPropertiesAllOfFromJSON(json: any): PaymentRequestParametersChannelPropertiesAllOf {
    return PaymentRequestParametersChannelPropertiesAllOfFromJSONTyped(json, false);
}

export function PaymentRequestParametersChannelPropertiesAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRequestParametersChannelPropertiesAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cvv': !exists(json, 'cvv') ? undefined : json['cvv'],
    };
}

export function PaymentRequestParametersChannelPropertiesAllOfToJSON(value?: PaymentRequestParametersChannelPropertiesAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cvv': value.cvv,
    };
}

