/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * 
 * @export
 */
export const PaymentRequestCurrency = {
    Idr: 'IDR',
    Php: 'PHP',
    Vnd: 'VND',
    Thb: 'THB',
    Myr: 'MYR'
} as const;
export type PaymentRequestCurrency = typeof PaymentRequestCurrency[keyof typeof PaymentRequestCurrency];


export function PaymentRequestCurrencyFromJSON(json: any): PaymentRequestCurrency {
    return PaymentRequestCurrencyFromJSONTyped(json, false);
}

export function PaymentRequestCurrencyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRequestCurrency {
    return json as PaymentRequestCurrency;
}

export function PaymentRequestCurrencyToJSON(value?: PaymentRequestCurrency | null): any {
    return value as any;
}

