/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */


/**
 * 
 * @export
 */
export const PaymentMethodReusability = {
    MultipleUse: 'MULTIPLE_USE',
    OneTimeUse: 'ONE_TIME_USE',
    XenditEnumDefaultFallback: "UNKNOWN_ENUM_VALUE"
} as const;
export type PaymentMethodReusability = typeof PaymentMethodReusability[keyof typeof PaymentMethodReusability];


export function PaymentMethodReusabilityFromJSON(json: any): PaymentMethodReusability {
    return PaymentMethodReusabilityFromJSONTyped(json, false);
}

export function PaymentMethodReusabilityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethodReusability {
    if (json !== "" || json !== null) {
        const key = Object.keys(PaymentMethodReusability)[Object.values(PaymentMethodReusability).indexOf(json)]
        return PaymentMethodReusability[key] === undefined ?
            PaymentMethodReusability['XenditEnumDefaultFallback'] : PaymentMethodReusability[key]
    }
    return json as PaymentMethodReusability;
}

export function PaymentMethodReusabilityToJSON(value?: PaymentMethodReusability | null): any {
    return value as any;
}

