/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { PaymentRequestCardVerificationResultsThreeDeeSecure } from './PaymentRequestCardVerificationResultsThreeDeeSecure';
import {
    PaymentRequestCardVerificationResultsThreeDeeSecureFromJSON,
    PaymentRequestCardVerificationResultsThreeDeeSecureFromJSONTyped,
    PaymentRequestCardVerificationResultsThreeDeeSecureToJSON,
} from './PaymentRequestCardVerificationResultsThreeDeeSecure';

/**
 * 
 * @export
 * @interface PaymentRequestCardVerificationResults
 */
export interface PaymentRequestCardVerificationResults {
    /**
     * 
     * @type {PaymentRequestCardVerificationResultsThreeDeeSecure}
     * @memberof PaymentRequestCardVerificationResults
     */
    threeDSecure: PaymentRequestCardVerificationResultsThreeDeeSecure | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestCardVerificationResults
     */
    cvvResult?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestCardVerificationResults
     */
    addressVerificationResult?: string | null;
}

/**
 * Check if a given object implements the PaymentRequestCardVerificationResults interface.
 */
export function instanceOfPaymentRequestCardVerificationResults(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "threeDSecure" in value;

    return isInstance;
}

export function PaymentRequestCardVerificationResultsFromJSON(json: any): PaymentRequestCardVerificationResults {
    return PaymentRequestCardVerificationResultsFromJSONTyped(json, false);
}

export function PaymentRequestCardVerificationResultsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRequestCardVerificationResults {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'threeDSecure': PaymentRequestCardVerificationResultsThreeDeeSecureFromJSON(json['three_d_secure']),
        'cvvResult': !exists(json, 'cvv_result') ? undefined : json['cvv_result'],
        'addressVerificationResult': !exists(json, 'address_verification_result') ? undefined : json['address_verification_result'],
    };
}

export function PaymentRequestCardVerificationResultsToJSON(value?: PaymentRequestCardVerificationResults | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'three_d_secure': PaymentRequestCardVerificationResultsThreeDeeSecureToJSON(value.threeDSecure),
        'cvv_result': value.cvvResult,
        'address_verification_result': value.addressVerificationResult,
    };
}

