/* tslint:disable */
/* eslint-disable */
/**
 * NOTE: This file is auto generated by Xendit.
 * Do not edit the class manually.
 * Improvements? Share your ideas at https://github.com/xendit/xendit-node
 */

import { exists, mapValues } from '../../runtime';
import type { CardParameters } from './CardParameters';
import {
    CardParametersFromJSON,
    CardParametersFromJSONTyped,
    CardParametersToJSON,
} from './CardParameters';
import type { DirectDebitParameters } from './DirectDebitParameters';
import {
    DirectDebitParametersFromJSON,
    DirectDebitParametersFromJSONTyped,
    DirectDebitParametersToJSON,
} from './DirectDebitParameters';
import type { EWalletParameters } from './EWalletParameters';
import {
    EWalletParametersFromJSON,
    EWalletParametersFromJSONTyped,
    EWalletParametersToJSON,
} from './EWalletParameters';
import type { OverTheCounterParameters } from './OverTheCounterParameters';
import {
    OverTheCounterParametersFromJSON,
    OverTheCounterParametersFromJSONTyped,
    OverTheCounterParametersToJSON,
} from './OverTheCounterParameters';
import type { PaymentMethodReusability } from './PaymentMethodReusability';
import {
    PaymentMethodReusabilityFromJSON,
    PaymentMethodReusabilityFromJSONTyped,
    PaymentMethodReusabilityToJSON,
} from './PaymentMethodReusability';
import type { PaymentMethodType } from './PaymentMethodType';
import {
    PaymentMethodTypeFromJSON,
    PaymentMethodTypeFromJSONTyped,
    PaymentMethodTypeToJSON,
} from './PaymentMethodType';
import type { QRCodeParameters } from './QRCodeParameters';
import {
    QRCodeParametersFromJSON,
    QRCodeParametersFromJSONTyped,
    QRCodeParametersToJSON,
} from './QRCodeParameters';
import type { VirtualAccountParameters } from './VirtualAccountParameters';
import {
    VirtualAccountParametersFromJSON,
    VirtualAccountParametersFromJSONTyped,
    VirtualAccountParametersToJSON,
} from './VirtualAccountParameters';

/**
 * 
 * @export
 * @interface PaymentMethodParameters
 */
export interface PaymentMethodParameters {
    /**
     * 
     * @type {PaymentMethodType}
     * @memberof PaymentMethodParameters
     */
    type: PaymentMethodType;
    /**
     * 
     * @type {PaymentMethodReusability}
     * @memberof PaymentMethodParameters
     */
    reusability: PaymentMethodReusability;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodParameters
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethodParameters
     */
    referenceId?: string;
    /**
     * 
     * @type {CardParameters}
     * @memberof PaymentMethodParameters
     */
    card?: CardParameters | null;
    /**
     * 
     * @type {DirectDebitParameters}
     * @memberof PaymentMethodParameters
     */
    directDebit?: DirectDebitParameters | null;
    /**
     * 
     * @type {EWalletParameters}
     * @memberof PaymentMethodParameters
     */
    ewallet?: EWalletParameters | null;
    /**
     * 
     * @type {OverTheCounterParameters}
     * @memberof PaymentMethodParameters
     */
    overTheCounter?: OverTheCounterParameters | null;
    /**
     * 
     * @type {VirtualAccountParameters}
     * @memberof PaymentMethodParameters
     */
    virtualAccount?: VirtualAccountParameters | null;
    /**
     * 
     * @type {QRCodeParameters}
     * @memberof PaymentMethodParameters
     */
    qrCode?: QRCodeParameters | null;
}

/**
 * Check if a given object implements the PaymentMethodParameters interface.
 */
export function instanceOfPaymentMethodParameters(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "type" in value;
    isInstance = isInstance && "reusability" in value;

    return isInstance;
}

export function PaymentMethodParametersFromJSON(json: any): PaymentMethodParameters {
    return PaymentMethodParametersFromJSONTyped(json, false);
}

export function PaymentMethodParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentMethodParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': PaymentMethodTypeFromJSON(json['type']),
        'reusability': PaymentMethodReusabilityFromJSON(json['reusability']),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'referenceId': !exists(json, 'reference_id') ? undefined : json['reference_id'],
        'card': !exists(json, 'card') ? undefined : CardParametersFromJSON(json['card']),
        'directDebit': !exists(json, 'direct_debit') ? undefined : DirectDebitParametersFromJSON(json['direct_debit']),
        'ewallet': !exists(json, 'ewallet') ? undefined : EWalletParametersFromJSON(json['ewallet']),
        'overTheCounter': !exists(json, 'over_the_counter') ? undefined : OverTheCounterParametersFromJSON(json['over_the_counter']),
        'virtualAccount': !exists(json, 'virtual_account') ? undefined : VirtualAccountParametersFromJSON(json['virtual_account']),
        'qrCode': !exists(json, 'qr_code') ? undefined : QRCodeParametersFromJSON(json['qr_code']),
    };
}

export function PaymentMethodParametersToJSON(value?: PaymentMethodParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': PaymentMethodTypeToJSON(value.type),
        'reusability': PaymentMethodReusabilityToJSON(value.reusability),
        'description': value.description,
        'reference_id': value.referenceId,
        'card': CardParametersToJSON(value.card),
        'direct_debit': DirectDebitParametersToJSON(value.directDebit),
        'ewallet': EWalletParametersToJSON(value.ewallet),
        'over_the_counter': OverTheCounterParametersToJSON(value.overTheCounter),
        'virtual_account': VirtualAccountParametersToJSON(value.virtualAccount),
        'qr_code': QRCodeParametersToJSON(value.qrCode),
    };
}

